language: python
python:
  - "3.6"

before install:
  - sudo apt-get update

# See http://conda.pydata.org/docs/travis.html
# Set up anaconda
install:
  - source scripts/get_miniconda.sh
  - conda env create -f scripts/conda_notebook.yml
  - source activate notebooks

# Testing and building
script: bash scripts/cibuild.sh

# Only CI on backend branch
branches:
  only:
  - backend   # test the notebooks branch

sudo: false  # route your build to the container-based infrastructure for a faster build
