language: python
python:
  - "3.6"

before install:
  - sudo apt-get update

rvm:
  - 2.4.1

before_script:

# Testing and building
script: bash scripts/cibuild.sh

# Only CI on backend branch
branches:
  only:
  - master     # if you are serving from master, change this accordingly

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer


sudo: false  # route your build to the container-based infrastructure for a faster build
