language: ruby

cache: bundler

rvm:
  - 2.4.1

before_script:
  - source scripts/get_miniconda.sh
  - conda env create -f scripts/nb_env.yml
  - source activate nb_env.yml
  - source deactivate nb_env.yml

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: source scripts/cibuild

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master     # test the gh-pages branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false  # route your build to the container-based infrastructure for a faster build
