language: ruby

cache: bundler

rvm:
  - 2.4.1
python:
  - "3.5"

before_script:
  - chmod +x ./scripts/cibuild # or do this locally and commit

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./script/cibuild

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master     # test the gh-pages branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false  # route your build to the container-based infrastructure for a faster build
