language: python
python:
  - "3.5"

install:
  - source scripts/get_miniconda.sh
  - conda env create -f scripts/conda_notebook.yml
  - source activate notebooks
  - pip install nbval
  - pip install GPy

before_script:
  - source scripts/get_miniconda.sh
  - conda env create -f scripts/nb_env.yml
  - source activate nb_env.yml
  - source deactivate nb_env.yml

script: ./scripts/cibuild

# branch whitelist backend only now
branches:
  only:
  - backend   # test the notebooks branch

sudo: false  # route your build to the container-based infrastructure for a faster build
