# Site settings
title: Module template
description: Lorem ipsum dolor sit amet understanding yourself in the universe tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
baseurl: "/Modules-template"
url: "https://trallard.github.io" # the base hostname & protocol for your site

# Author's information
author:
  name: Tania Allard

# Images used in the landing page
logo: "./images/logo-sheffield.png"
card_image: "./images/dna.jpg" #default card image to be shown


# Build settings
markdown: kramdown
highlighter: rouge
include: ['_pages']
exclude:
  - .gitignore
  - README.md
  - vendor
  - .travis.yml
  - Gemfile*

# To ensure the links work properly
permalink: pretty

# Additional gems
plugins_dir:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - jekyll-titles-from-headings

# SASS directory
sass:
  style: compressed
  sass_dir: _sass

# Where things are
source: .
destination: ./_site
data_dir: ./_data

# Collections: note each of this corresponds to a module
collections:
  Day1:
    output: true
  Day2:
    output: true


# If your notebooks are in an Azure library add the url here,
# otherwise comment by adding a #
azure: "https://notebooks.azure.com/trallard/libraries/BAD-days"
