# Site settings
title: Module template
description: Lorem ipsum dolor sit amet understanding yourself in the universe tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
baseurl: ""
url: "http://trallard.github.io" # the base hostname & protocol for your site


# About
author:
  name: Tania Allard

#Extra parameters
github_username:
project_repository:
disqus_shortname:
g-analytics:

# Build settings
markdown: kramdown
highlighter: rouge
include: ['_pages']
highlighter: rouge
exclude:
  - .gitignore
  - README.md
  - nb_jekyll.py
  - jekyll.tpl
  - nb_replace.py
  - vendor
  - .travis.yml
  - Gemfile*
  - reveal.js

# to ensure the links work properly
permalink: pretty

# Additional gems
gems:
  - jekyll-seo-tag
  - jekyll-sitemap

# SASS directory
sass:
  style: compressed
  sass_dir: _sass


# Collections: note each of this corresponds to a module
collections:
  Day1:
    output: true
  Day2:
    output: true
